apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: zabbix
  labels:
    app: zabbix-agent
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      hostNetwork: true
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent2:7.0-alpine-latest
          ports:
            - containerPort: 10050
              name: zabbix-agent
          envFrom:
            - configMapRef:
                name: zabbix
          env:
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
